#!/bin/bash
########################################################
# Script: AssignmentSystemReport.sh
# Description: Will generate a system report based on hardware, network configuration, system information and status.
# Name: Sehajdeep Singh
# Date: $(dateTime)
########################################################
Username=$(whoami)
dateTime=$(date +"%Y-%m-%d %H:%M:%S")
INTRO="System Report generated by $Username, $dateTime
"
echo "$INTRO"

#System Information

Hostname=$(hostname)

distroVersion=$(cat /etc/*release | grep "PRETTY_NAME" | cut -d'=' -f2 | tr -d ' " ')

upTime=$(uptime -p)

SystemInformation="System Information
------------------
Hostname: $Hostname
OS: $distroVersion
Uptime: $upTime"

echo "$SystemInformation"

# Hardware Information

CPU=$(lscpu | grep "Model name:" | awk -F ': ' '{print $2}')

# Get the CPU speedc
cpuSpeed=$(sudo dmidecode -t processor | grep -E "Speed" | head -n 1)
maxCpuSpeed=$(cat /proc/cpuinfo | grep "cpu MHz" | awk '{print $NF; exit}')

# Get the installed RAM size
RAM=$(free -h | awk '/^Mem:/{print $2}')

# Get disk information
disks=$(lsblk -d -o NAME,MODEL,SIZE | grep -vE "^NAME")

# Get video card information
video=$(lspci | grep -iE "vga|3d|display" | awk -F ": " '{print $2}')

# Generate the hardware information report
Hard_info="
Hardware Information
--------------------
CPU: $CPU
Speed: $cpuSpeed (Max: $maxCpuSpeed MHz)
RAM: $RAM
Disk(s): $disks
Video: $video"

# Print the report
echo "$Hard_info"


FQDN=$(hostname -f)

# Get the host address
hostAddress=$(hostname -I | awk '{print $1}')

# Get the gateway IP
gatewayIP=$(ip route | grep default | awk '{print $3}')

# Get the DNS server IP
dnsServer=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}' | head -n1)

# Get network interface information
interfaceName=$(ip -o link show | awk -F': ' '{print $2}' | grep -v lo)
interfaceIP=$(ip -o -f inet addr show | awk '/scope global /{print $4}')

# Generate the network information report
Net_info="
Network Information
-------------------
FQDN: $FQDN
Host Address: $hostAddress
Gateway IP: $gatewayIP
DNS Server: $dnsServer

Interface Name: $interfaceName
IP Address: $interfaceIP"

# Print the report
echo "$Net_info"

userLoggedIn=$(who | cut -d' ' -f1 | sort | uniq | tr '\n' ',' | sed 's/,$//')

# Get disk space
diskSpace=$(df -h --output=target,avail | grep -vE 'Filesystem|tmpfs|cdrom')
# Get process count
processCount=$(ps aux --no-headers | wc -l)

# Get load averages
loadAverages=$(cat /proc/loadavg | awk '{print $1",", $2",", $3}')

# Get memory allocation
memoryAllocation=$(free -h | awk '/^Mem:/{print $3"/"$2}')

# Get listening network ports
listeningPorts=$(ss -tuln | awk 'NR > 1 {print $4}' | cut -d ':' -f 2 | sort -n | uniq | tr '\n' ',')
UFWRules=$(sudo ufw status )

# Generate the system status report
SysStatus="
System Status
-------------
Users Logged In: $userLoggedIn
Disk Space: $diskSpace
Process Count: $processCount
Load Averages: $loadAverages
Memory Allocation: $memoryAllocation
Listening Network Ports: $listeningPorts
UFW Rules: $UFWRules"

# Print the report
echo "$SysStatus"

#Output the system Report
cat << EOF

EOF
